# Session 5: From Single to Multiple Values: Arrays and NumPy

### Creating Arrays
In Python, arrays can be created manually.

#### Example: Creating an array manually


In [2]:
import numpy as np

my_array = np.array([1, 2, 3,4])
print(my_array)

[1 2 3 4]


They can also be created quickly and automatically using NumPy function`linspace` to generate evenly spaced points in an interval: `np.linspace(start, stop, number of points)`

### Practice Problem 1
- Create a NumPy array `my_array` with values `[5, 10, 15, 20, 25]`.
- Multiply each element by 3 and print the result.

#### Solution:


In [8]:
my_array = np.array([5, 10, 15, 20, 25])
my_array2 = np.array ([5, 10, 15, 20, 25]) *3 

print(my_array2)

[15 30 45 60 75]


 ### Practice Problem 2

 Write a function that takes two arrays (they have to be the same size), adds them together, and then returns the mean of the summed array.

In [9]:
my_array1 = np.array([5, 10, 15, 20, 25])
my_array2 = np.array ([12, 14, 8, 9, 2])

In [10]:
def mean_array(my_array1, my_array2):
    sum_array = my_array1 + my_array2
    mean = np.mean(sum_array)
    return mean

mean = mean_array(my_array1, my_array2)
print(mean)



24.0


### Practice Problem 3
- Create an array of numbers with the values `[10, 20, 30, 40, 50]`.
- Change the second element to 25.
- Print the modified array.

#### Solution:


In [23]:
array = [10, 20, 30, 40, 50]
array[1] = 25
#print(array)

array[3]= 45
array[4] = 55
print(array)

[10, 25, 30, 45, 55]


In [28]:
my_array = np.array([5, 15, 15, 20, 25])
my_array[0:3]

array([ 5, 15, 15])

### Practice Problem 4

Create a 6 by 10 (6 rows and 10 columns) 2D numpy array in which the first row is all 1's, the rest of the second column is all 5's, and the rest of the array is all 0's.

### Solution:

In [4]:
array_2d =  np.array ([[0,1], [2,3], [4,5]])
print(array_2d)

[[0 1]
 [2 3]
 [4 5]]


In [7]:
array_2d = np.zeros((3,2)) #3 rows, 2 columns
print(array_2d)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
array_2d = np.zeros ((6,10))
print(array_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
array_2d[0] = 1
array_2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
array_2d[1:,1] = 5
array_2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
array_2d[4, 5] = 7 #rows, columns
array_2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 7., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Practice Problem 5

Write a function that takes an array and a threshold number, and returns just the values that are greater than that threshold. 

## Solution: